// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lanlhnmmimdvdxmqzzzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxhbmxobm1taW1kdmR4bXF6enp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY3NzU3ODMsImV4cCI6MjA1MjM1MTc4M30.fJIXQ8jJujfocwSH8NItEOku8JGRa9e4923QALQeO34";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);